name: sfrmaker
channels:
- conda-forge
- defaults
- conda-forge/label/dev
dependencies:
- python=3.6.*
- ipython
- matplotlib
- pyyaml
- numpy
- pandas
- gdal
- fiona
- rasterio>=1.0
- rasterstats
- shapely
- rtree
- pyproj>=2.0
- pyshp
- flopy
