package_version: 'mfnwt'
package_name: 'tf'
output_path: '.'
# any arguments to Lines.to_sfr() or SFRData
# can be supplied as top-level keys
model_length_units: 'feet'
modelgrid:
  shapefile: grid.shp
  icol: i  # attribute field with row numbers
  jcol: j  # attribute field with column numbers
flowlines:
  NHDFlowlines: NHDPlus/NHDSnapshot/Hydrography/NHDflowline.shp
  PlusFlowlineVAA: NHDPlus/NHDPlusAttributes/PlusFlowlineVAA.dbf
  PlusFlow: NHDPlus/NHDPlusAttributes/PlusFlow.dbf
  elevslope: NHDPlus/NHDPlusAttributes/elevslope.dbf
dem:
  filename: dem_26715.tif
  elevation_units: meters
set_streambed_top_elevations_from_dem: True
